name: PluginHttpServer # the plugins name as it should appear in the plugin list /pl
version: 1.0 # the plugin's version
author: Crispin
main: org.distributed.DistributedServerPlugin
api-version: 1.19
description: The plugin that connects the distributed system